[package]
edition = "2024"
name = "pose-de-game"
version = "0.1.0"

[features]
coreml = ["ort/coreml"]
default = []
openvino = ["dep:openvino"]

[dependencies]
anyhow = "1.0.100"
bevy = { version = "0.17.3", features = ["mp3"] }
clap = { version = "4.5.53", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_bytes = "0.11"
serde_cbor = "0.11.2"

# detect
fast_image_resize = "5.4.0"
image = "0.25.9"
nokhwa = { version = "0.10.10", features = ["input-native"] }
openvino = { version = "0.9.1", optional = true }
ort = { version = "2.0.0-rc.11", features = ["cuda"] }
tract-onnx = "0.22.0"

# menu
bevy_flair = "0.6.0"
